### ISSUE TITLE
Where is the rolling_signal_list variable defined

### ISSUE THREAD

**Issue by pranavlal** [kieran-mackle/AutoTrader#51]
**Describe the bug**
Visual studio code is unable to find the variable caled rolling_signal_list
**To Reproduce**
1. I am trying to use your divergence indicator in my own code.  '...'
2.  What routines do I need to use it?
3.  I have taken ema, classify_swings, find_swings and detect_divergence.  
4.  What other code do I need to include for the above routines to work?

**Expected behavior**
I should be able to use the detect_divergence routine.

My idea behind using the divergence ndicator is to detect when a bearish trend is about to begin. I have a long only machine learning model which works when I need to buy stocks but I need to sell on time. My idea is to detect  a bearish divergence. If that happens, I know the price could fall therefore take profit and move on.

**Comment by kieran-mackle** [comment]
Hi @pranavlal,

Please provide a minimal snippet of code which can be run to reproduce any error you are seeing. I am not exactly sure what the issue here is.

In case you haven't seen it, I have written a post about using the divergence indicators, you can find that [here](https://kieran-mackle.github.io/AutoTrader/2021/11/08/detecting-divergence.html). It may be of help.

**Comment by jmcph4** [comment]
@pranavlal 

```
$ git rev-parse HEAD
9478b6253bcd9456ad3dee99cd8b961950196ba3
$ grep -rin "def rolling_signal_list" autotrader
autotrader/indicators.py:934:def rolling_signal_list(signals: Union[list, pd.Series]) -> list:
```

**Comment by jmcph4** [comment]
This seems like a good candidate for closure given there's no minimally reproducible bug.
